// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOWYKiEVIDDVTRT7TGLSkE_Pc-3g5G3CY',
    appId: '1:414153424043:android:e2f906709eaeb8aacbcbee',
    messagingSenderId: '414153424043',
    projectId: 'brahmansh-a4c4e',
    storageBucket: 'brahmansh-a4c4e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOWYKiEVIDDVTRT7TGLSkE_Pc-3g5G3CY',
    appId: '1:414153424043:android:e2f906709eaeb8aacbcbee',
    messagingSenderId: '414153424043',
    projectId: 'brahmansh-a4c4e',
    storageBucket: 'brahmansh-a4c4e.firebasestorage.app',
    iosClientId: '976344297784-arkpj1onupfb8athiqivpi70d6oe9hdj.apps.googleusercontent.com',
    iosBundleId: 'com.brahmanshtalk.astrologerr',
  );

}